apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service  # <--- Dynamic Name
spec:
  type: {{ .Values.service.type }}   # <--- Variable from values.yaml
  selector:
    app: {{ .Release.Name }}-2048    # <--- MUST match the labels in deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
